### ISSUE TITLE
Sumário citando Ciência da Computação

### ISSUE THREAD

**Issue by NilsonCesar** [Universidade-Livre/matematica#4]
Alô! Percebi que o sumário possui alguns erros, talvez porque seja semelhante ao de Ciência da Computação da Universidade-Livre. Aqui os que encontrei (os erros estarão em negrito):

- acreditamos que uma formação completa abrange mais do que simplesmente **CC**
- Estar de acordo com o que espera-se do Currículo de **Ciências da Computação**

De novo, todas essas citações estão presentes na parte do sumário (README.md).

**Comment by Camilotk** [comment]
Corrigido! Obrigado! ❤️

**Comment by NilsonCesar** [comment]
Acabei de notar que na seção "Antes de começar" também está citando Ciência da computação.
