### ISSUE TITLE
Estruturação da grade curricular

### ISSUE THREAD

**Issue by Shnrqpdr** [Universidade-Livre/matematica#5]
# Ordem de disciplinas

Acredito que a ordem da grade curricular atual está um pouco inconsistente, e caso o aluno deseje segui-la, possuirá lacunas importantes para atingir uma formação básica sólida para então progredir em cursos mais avançados de matemática. Sendo assim, vou estruturar essa issue de acordo com os tópicos da grade curricular atual, listando meus comentários:

## Introdução ao Cálculo e a Matemática

Visando o fato de que o curso é um curso pra matemática, eu acredito não haver necessidade de dedicar-se 4 horas/semana para python e algoritmos, pois, se vocês notarem, há somente um outro curso estritamente de programação ao decorrer da grade. Acredito que 2 horas/semana seria o suficiente, e distribuiria essas 2 horas restantes para "Ingredientes básicos para o Cálculo" e "Lógica e Matemática Discreta", que é bastante importante para as materiais que virão a seguir.

## Aprofundamento no Cálculo e Início da Física Geral

"Cálculo I" é, sem sombra de dúvidas, o curso que mais te dá "raça" pra poder resolver contas ao decorrer de uma graduação, isso porque nesse curso você faz MUITO exercício. Sendo assim, acredito ser importante acrescentar 1hora a mais de dedicação por semana, o que tornaria o aprendizado mais frutífero.

Eu levaria, também, Física Geral I para a próxima etapa da grade, pois Física I carrega um grande arsenal de ferramentas que vemos em Cálculo I, então, pra ser mais proveitoso, é interessante que Física I seja feita após os cursos de Cálculo I e "Álgebra Linear".

Em contrapartida, eu traria Teoria dos Números para essa etapa do curso, visto que é um curso bastante importante para o curso "Análise na Reta", não no sentido de conteúdo, mas no sentido de aprender a se trabalhar com relações matemáticas, pois esse seria o primeiro curso que o aluno usaria, com clareza, relações baseadas em teoria dos conjuntos, ganhando força pros cursos que virão.

## Aprofundamento no Cálculo e Física

Análise na Reta é um curso MUITO difícil do ponto de vista prático (de exercício e abstração), engana-se quem pensa que não é. Dito isso, acredito que seria mais interessante que Análise na Reta fosse passada para a próxima parte do curso, colocando "Estruturas Algébricas" no lugar, que tem como pré requisito Teoria dos Números feita anteriormente, por dois motivos:
         1 - O aluno vai conseguir ainda se lembrar de grande parte da grade e do acúmulo de conhecimento de teoria dos números
         2 - O aluno vai ganhar mais maturidade matemática pra análise na reta e os próximos cursos

Como Física I entraria nessa grade, Fisica II passaria para a próxima.

## Cálculo e Física Avançado

Análise na Reta entraria nessa etapa, sendo o principal curso, entrando no lugar de Análise Complexa.
Cálculo IV entraria nesta etapa, onde seu nome poderia ser mudado para "Física-Matemática" ou como "Métodos Matemáticos" como é visto em muitos lugares. (Falarei mais desse ponto em um remark).
Física III passaria para a frente dando lugar à Física II e o resto se manteria.

## Tópicos Matemáticos 

"Tópicos Matemáticos" trocaria de nome para "Matemática Moderna"

Estruturas Algébricas que passou pra trás daria lugar à Física Geral III, completando assim a grade mínima de física básica do curso de matemática. 
"Variável Complexa" trocaria de nome para "Cálculo com variável complexa": limites, derivação, integração, refere-se ao cálculo diferencial e integral, portanto deve vir no nome. Seria interessante tal curso cobrir até a parte de "Teorema dos Resíduos" que é a principal ferramenta do cálculo com variável complexa.

Entraria o curso de Análise no Rn.

Teoria dos Grafos ocupando somente 4 semanas, também abriria espaço para adicionar o curso de Álgebra Exterior.

## Teoria Avançada

Retiraria Física Moderna e colocaria Geometria Diferencial.
Retiraria Equações Diferenciais Parciais, cujo conteudo entraria na parte dos métodos matemáticos (ou fisica matemática), e colocaria Análise Complexa.

# Observações

## Análise Complexa 

Análise Complexa é um dos cursos mais difíceis do mestrado de matemática pura que eu conheço, não consigo conceber a ideia de ele ser oferecido num curso de graduação, tampouco em um curso cujo objetivo é ser autoditada. É necessário tutela, muito conhecimento abstrato e maturidade matemática pra se lidar com esse curso, por isso ele entraria na parte de teoria avançada, como um "plus"

## Física Matemática (ou Métodos Matemáticas)

Englobaria Sequências, Convergência, Séries, Método de Frobenius (resolução de e.d.o's via séries), Séries de Fourier,  Transformada de Fourier e Equações Diferenciais Parciais (cuja solução pode ser obtida via separação de variáveis).

**Comment by Camilotk** [comment]
@Shnrqpdr as mudanças em relação à organização foram feitas nos commits: b917a5b9af0540838f399b40aee5d9b7cd829ca5, 2c539c5e9ffedd580504773706cab30cb0bae0ed, 5b60f56565012c257552af3c7769511a2b10fea2, ffd6bb8629de875202324c1a7d0ad3b26ec61921, e68051c1339d3a09626166264385b7a8cab79bf1, dca4c22137d4749604b37b9165e0d702bb048706, 8603828c813b5218642078d4f6b76533fd0721ed e 16d1126cfbc9f481e8aa6538aab6fdaeb98ecfde.

Se tiver algum feedback de algo que deixei passar a respeito de organização manda que também faço as mudanças necessárias.

A parte de conteúdos em substituição ou adicionar novos vou começar uma pesquisa de conteúdos abertos relacionados aos temas sugeridos e em breve faço as mudanças necessárias.
